#pragma comment(lib, "glew32.lib")
#pragma comment(lib, "core.lib")
#pragma comment(lib, "opengl32.lib")
#pragma comment(lib, "di_rtlib.lib")
#pragma comment(lib, "material.lib")
#pragma comment(lib, "libxsd.lib")
#pragma comment(lib, "assimp.lib")